name = "fdelpozo/raffle"
version = "0.0.0"
compiler = "v1.1.13"
plutus = "v3"
license = "Apache-2.0"
description = "Aiken contracts for project 'txalata/raffle'"

[repository]
user = "fdelpozo"
project = "raffle"
platform = "github"

[[dependencies]]
name = "aiken-lang/stdlib"
version = "v2.2.0"
source = "github"

[config]
